version: '3.1'
services:
  web:
    build: docker/python
    links:
      - db
    ports:
      - 8000:8000
    volumes:
      - .:/project:rw
    environment:
      - DJANGO_SETTINGS_MODULE=mytemplate.settings
  db:
    image: postgres:10.3-alpine
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=django